import type { NextPage } from 'next'
import Head from 'next/head'
import { FormEvent, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [result, setResult] = useState();

  const promptTeemplate: string = ``;

  async function onSubmit(event: FormEvent) {
    event.preventDefault();
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }

      setResult(data.result);      
    } catch(error: any) {
      console.error(error);
      alert(error.message);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Market Compywriting Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Market Copy Inputs</h3>
        <form onSubmit={onSubmit}>
          <input type="submit" value="Generate Copy" />
        </form>
        <div className={styles.result}>{result}</div>
      </main>
    </div>
  )
}

export default Home
